// 指定使用 Protocol Buffers 第 3 版語法 (proto3)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/greeting.proto

// 定義 Protobuf 的命名空間 (Package)，防止不同 proto 檔之間的名稱衝突

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定義請求訊息格式 (Message)
type HelloRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 欄位定義格式：<資料型態> <欄位名稱> = <欄位編號>;
	// 注意：數字 1 是「欄位標籤編號」(Field Tag Number)，
	// 在二進位序列化時用來標識欄位，而不是代表預設值或順序。
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // 用戶端傳入的問候名稱
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 用戶端傳入的自訂問候文字
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_proto_greeting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_greeting_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 定義回應訊息格式 (Message)
type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`          // 服務端回傳的問候回應文字
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 服務端處理完成時的 Unix 時間戳記 (秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_proto_greeting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_proto_greeting_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *HelloResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_greeting_proto protoreflect.FileDescriptor

const file_proto_greeting_proto_rawDesc = "" +
	"\n" +
	"\x14proto/greeting.proto\x12\bgreeting\"<\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\rHelloResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2N\n" +
	"\x0fGreetingService\x12;\n" +
	"\bSayHello\x12\x16.greeting.HelloRequest\x1a\x17.greeting.HelloResponseB\x19Z\x17grpc-sample/proto/pb;pbb\x06proto3"

var (
	file_proto_greeting_proto_rawDescOnce sync.Once
	file_proto_greeting_proto_rawDescData []byte
)

func file_proto_greeting_proto_rawDescGZIP() []byte {
	file_proto_greeting_proto_rawDescOnce.Do(func() {
		file_proto_greeting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_greeting_proto_rawDesc), len(file_proto_greeting_proto_rawDesc)))
	})
	return file_proto_greeting_proto_rawDescData
}

var file_proto_greeting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_greeting_proto_goTypes = []any{
	(*HelloRequest)(nil),  // 0: greeting.HelloRequest
	(*HelloResponse)(nil), // 1: greeting.HelloResponse
}
var file_proto_greeting_proto_depIdxs = []int32{
	0, // 0: greeting.GreetingService.SayHello:input_type -> greeting.HelloRequest
	1, // 1: greeting.GreetingService.SayHello:output_type -> greeting.HelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_greeting_proto_init() }
func file_proto_greeting_proto_init() {
	if File_proto_greeting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_greeting_proto_rawDesc), len(file_proto_greeting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_greeting_proto_goTypes,
		DependencyIndexes: file_proto_greeting_proto_depIdxs,
		MessageInfos:      file_proto_greeting_proto_msgTypes,
	}.Build()
	File_proto_greeting_proto = out.File
	file_proto_greeting_proto_goTypes = nil
	file_proto_greeting_proto_depIdxs = nil
}
